GET http://localhost:5000/users
Authorization: Bearer 
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "mshinr",
    "email": "email@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "email@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
PATCH http://localhost:5000/users/85
Content-Type: application/json

{
    "username": "batang",
    "email": "batang@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}